# Generated by Django 4.1 on 2024-09-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['user_type'], 'permissions': [('can_view_custom_content', 'Can view custom content'), ('can_edit_custom_content', 'Can edit custom content')], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
    ]
